modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/${repoUser}/${repoName}/issues"
license = "LGPL-3.0"

[[mods]] #mandatory
modId="${modId}"
version="${version}"
displayName = "${modName}"
updateJSONURL = "https://raw.githubusercontent.com/${repoUser}/${repoName}/${minecraftVersion}/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/edit-sign"
logoFile="logo.png"
authors = "RakSrinaNa"
description = '''Allow you to edit signs without breaking them.'''

[[dependencies.editsign]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.editsign]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.editsign]]
modId = "cloth-config"
mandatory = false
versionRange = "[6.0.0,)"
ordering = "NONE"
side = "CLIENT"
