modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/${repoUser}/${repoName}/issues"
license = "LGPL-3.0"

[[mods]] #mandatory
modId="${modId}"
version="${version}"
displayName = "${modName}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/edit-sign"
logoFile="logo.png"
authors = "Rakambda"
description = '''Allow you to edit signs without breaking them.'''

[[dependencies.editsign]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.editsign]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.editsign]]
modId = "cloth-config"
mandatory = false
versionRange = "[8.0.0,)"
ordering = "NONE"
side = "CLIENT"
