changelog:
  exclude:
    labels:
      - "type: 📚 dependencies"
  categories:
  - title: "⚠ Breaking"
    labels:
    - "⚠ Breaking"
  - title: "🚀 Features"
    labels:
    - "type: 🧱 enhancement"
  - title: "🐛 Fixes"
    labels:
    - "type: 🐛 bug"
  - title: "🐛 Beta Fixes"
    labels:
    - "type: 🐛 beta bug"
  - title: Other Changes
    labels:
       - "*"
