changelog:
  exclude:
    labels:
      - "type: 📚 dependencies"
  categories:
  - title: "🚀 Features"
    labels:
    - "type: 🧱 enhancement"
  - title: "🐛 Fixes"
    labels:
    - "type: 🐛 bug"
  - title: Other Changes
    labels:
       - "*"
