[versions]
modmenu-version = "3.0.0"
cloth-config-fabric-version = "6.0.43"
cloth-config-forge-version = "6.0.43"
lombok-version = "1.18.22"
minecraft-version = "1.18"
fabric-loader-version = "0.12.8"
fabric-api-version = "0.43.1+1.18"
forge-version = "1.18-38.0.5"

curse-version = "1.4.0"
modrinth-version = "1.2.1"
names-version = "0.39.0"
fabric-loom-version = "0.10.62"

[libraries]
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu-version" }
clothConfigFabric = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version.ref = "cloth-config-fabric-version" }
clothConfigForge = { group = "me.shedaniel.cloth", name = "cloth-config-forge", version.ref = "cloth-config-forge-version" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok-version" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft-version" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader-version" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api-version" }
forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge-version" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]

[plugins]
curse = { id = "com.matthewprenger.cursegradle", version.ref = "curse-version"}
modrinth = { id = "com.modrinth.minotaur", version.ref = "modrinth-version"}
names = { id = "com.github.ben-manes.versions", version.ref = "names-version" }
loom = { id = "fabric-loom", version.ref = "fabric-loom-version" }
