# Fabric https://modmuss50.me/fabric.html

[versions]
lombok-version = "1.18.26"
jetbrains-annotations-version = "24.0.1"
gson-version = "2.10.1"
log4j2-version = "2.20.0"

minecraftVersion = "1.19.4"
fabric-loader-version = "0.14.17"
fabric-api-version = "0.75.3+1.19.4"
forge-version = "1.19.4-45.0.0"
forgeMappingsVersion = "1.19.3"

# Mod dependencies
modmenu-version = "6.1.0-rc.1"
clothConfigVersion = "10.0.96"

fabric-loom-version = "1.1.10"
forge-plugin-version = "5.1.68"
curse-version = "1.4.0"
modrinth-version = "2.7.5"
names-version = "0.46.0"

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok-version" }
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations-version" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson-version" }
log4j2 = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j2-version" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraftVersion" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader-version" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api-version" }
forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge-version" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu-version" }
clothConfigFabric = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version.ref = "clothConfigVersion" }
clothConfigForge = { group = "me.shedaniel.cloth", name = "cloth-config-forge", version.ref = "clothConfigVersion" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]

[plugins]
curse = { id = "com.matthewprenger.cursegradle", version.ref = "curse-version"}
modrinth = { id = "com.modrinth.minotaur", version.ref = "modrinth-version"}
names = { id = "com.github.ben-manes.versions", version.ref = "names-version" }
loom = { id = "fabric-loom", version.ref = "fabric-loom-version" }
forge = { id = "net.minecraftforge.gradle", version.ref = "forge-plugin-version" }
