# Fabric https://modmuss50.me/fabric.html

[versions]
lombok-version = "1.18.22"
jetbrains-annotations-version = "23.0.0"
gson-version = "2.8.9"
log4j2-version = "2.17.1"
minecraftVersion = "1.18.2"
fabric-loader-version = "0.13.3"
fabric-api-version = "0.47.8+1.18.2"
forge-version = "1.18.1-39.0.0"
modmenu-version = "3.0.1"
clothConfigVersion = "6.2.57"

fabric-loom-version = "0.11.29"
forge-plugin-version = "5.1.27"
curse-version = "1.4.0"
modrinth-version = "1.2.1"
names-version = "0.42.0"

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok-version" }
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations-version" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson-version" }
log4j2 = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j2-version" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraftVersion" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader-version" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api-version" }
forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge-version" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu-version" }
clothConfigFabric = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version.ref = "clothConfigVersion" }
clothConfigForge = { group = "me.shedaniel.cloth", name = "cloth-config-forge", version.ref = "clothConfigVersion" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]

[plugins]
curse = { id = "com.matthewprenger.cursegradle", version.ref = "curse-version"}
modrinth = { id = "com.modrinth.minotaur", version.ref = "modrinth-version"}
names = { id = "com.github.ben-manes.versions", version.ref = "names-version" }
loom = { id = "fabric-loom", version.ref = "fabric-loom-version" }
forge = { id = "net.minecraftforge.gradle", version.ref = "forge-plugin-version" }
