name: CI

on:
  push:

env:
  APP_JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Restore keystore
        env:
          KEYSTORE_FORGE_MODS: ${{ secrets.KEYSTORE_FORGE_MODS }}
        if: env.KEYSTORE_FORGE_MODS != null
        run: |
          echo "${{ secrets.KEYSTORE_FORGE_MODS }}" > keystoreForgeMods.jks.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_FORGE_MODS_PASSPHRASE }}" --batch keystoreForgeMods.jks.asc > keystoreForgeMods.jks

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}

      - name: Set gradle permissions
        run: chmod +x gradlew

      - name: Check project
        uses: gradle/gradle-build-action@v2.6.0
        env:
          ORG_GRADLE_PROJECT_forgeKeyStore: keystoreForgeMods.jks
          ORG_GRADLE_PROJECT_forgeKeyStoreAlias: ${{ secrets.KEYSTORE_FORGE_MODS_ALIAS }}
          ORG_GRADLE_PROJECT_forgeKeyStorePass: ${{ secrets.KEYSTORE_FORGE_MODS_STORE_PASS }}
          ORG_GRADLE_PROJECT_forgeKeyStoreKeyPass: ${{ secrets.KEYSTORE_FORGE_MODS_KEY_PASS }}
          ORG_GRADLE_PROJECT_forgeSignSHA1: f927f4701bf4c0620c7bd0a501ce278f5e5ecc62
        with:
          arguments: |
            clean
            build

      - name: Upload mod file
        uses: actions/upload-artifact@v3
        with:
          name: mod-file
          path: |
            build/libs/*.jar
          if-no-files-found: error
          retention-days: 14
